
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Toolkit;


public class MapPane extends javax.swing.JPanel {

    /**
     * Creates new form MapPane
     */
	
    public MapPane() {
        initComponents();
    }
   
    public void paint(Graphics g){
    	super.paint(g);
    	
    	//mapPane 크기
    	//g.setColor(Color.LIGHT_GRAY);
    	//g.drawRect(0, 0, getWidth(), getHeight());
    	
    	//이미지 들어갈 위치 확인
    	//g.setColor(Color.WHITE);
    	//g.fillRect(0, 0, 600, 580);
    	//g.setColor(Color.BLACK);
    	//g.drawRect(0, 0, 600, 579);
    	
    	//맵 이미지 (600*580)
    	java.awt.Image map = Toolkit.getDefaultToolkit().getImage("./images/map.png");
    	g.drawImage(map, 0, 0, 600, 580, this);
    	
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
